name: Get GMB Data

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *' 
    
    
jobs:
  GetGMBRoute:
    permissions:
      id-token: write
      contents: write
      pages: write

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r action/requirements.txt

      - name: execute py script 
        run: |
          python action/GMB_Route.py

      
      #- name: commit files
      #  run: |
      #    git config --local user.email "action@github.com"
      #    git config --local user.name "GitHub Action"
      #    git add -A
      #    git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            output/*.json
            log/*.log
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: main