name: Get all Bus Route Data

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *' 
    
jobs:
  FGDB:
    permissions:
      id-token: write
      contents: write
      pages: write

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r action/requirements.txt

      - name: execute py script 
        run: |
          python action/FGDB_BUS.py
          python action/FGDB_GMB.py
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'FGDB'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


  GetRoute:
    permissions:
      id-token: write
      contents: write
      pages: write

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r action/requirements.txt

      - name: execute py script 
        run: |
          python action/GetRoute.py
        # python action/KMB_Route.py
        # python action/CTB_Route.py
        # python action/NLB_Route.py
        # python action/GMB_Route.py
        # python action/MTR_BUS_Route.py

      
      #- name: commit files
      #  run: |
      #    git config --local user.email "action@github.com"
      #    git config --local user.name "GitHub Action"
      #    git add -A
      #    git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            output/*.json
            log/*.log
          #FGDB/BUS/*.json
          #FGDB/GMB/*.json
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: main